# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.62.1"
gem "rubocop-github", "~> 0.17.0"
gem "rubocop-performance", "~>1.14.2"

gem "rubocop-rails", "~> 2.5"
gem "rubocop-rspec", "~> 2.12.1"